/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_cache_Cache */

#ifndef _Included_com_jni_cache_Cache
#define _Included_com_jni_cache_Cache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_cache_Cache
 * Method:    add
 * Signature: (Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_com_jni_cache_Cache_add
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_jni_cache_Cache
 * Method:    get
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jni_cache_Cache_get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jni_cache_Cache
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jni_cache_Cache_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
