/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_hash_HashEncryptor */

#ifndef _Included_com_jni_hash_HashEncryptor
#define _Included_com_jni_hash_HashEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_hash_HashEncryptor
 * Method:    md5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_hash_HashEncryptor_md5
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
